---

- name: obtain jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  changed_when: False

- set_fact:
    jenkins_admin_password: "{{ initial_admin_password.stdout }}"

- debug:
    msg: "The default admin password is {{ jenkins_admin_password }}"
    verbosity: 2
